name: CI
on:
  pull_request:

jobs:
  ci:
    name: Check lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test -A
      - name: Check format
        run: deno fmt --check
      - name: Type check
        run: deno check mod/**.ts
      - name: Build
        run: deno run -A build_npm.ts
